name: worksphere-deployment
on:
  push:
      branches: [ main ]

jobs:
  tests-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/chekout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: install dependencies
        run: npm ci

      - name: run tests
        run: npm run test

      - name: build vite
        run: npm run build

      - name: save the build
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist/

  delpoy-aws:
    runs-on: ubuntu-latest
    needs: test-and-build

    steps:
      - name:  get the built coded
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: dist/

      - name: zws configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:

      - name deploy too aws s3:
        run: aws s3 sync dist/ s3://worksphere-m --delete